language: java
install: true
script: gradle publishGhPages --debug
env:
  global:
    secure: HrqDfIv/wWE3FyF21eJ1k1M1AvJQte7+1iFDBeGVpW3YEM8aERGoDwm3aQfW/l1hTqv8ukiHau6VuzuvB+tgughV14iyIlGnI67k4P6MD00RMouiSQqEhCSQpO4V+yLUGOyxTUHjPosX9u+BDYR2nopNg1ncj0XIiJKVUd+jaXOb8EjNHXwZzMCMssgrLDIiuy6ROpV+x2U8vhfqi6HpwM8wgnaf/3E+n4Sa6tdBAuZp1FatEVJwrIcaB2Ry8jclRBWUzMx6dGaMda2P2kfAR6B3RU4vpHZiYQg0dBZV68UcCLRRtwhvcRVo5sPwfIQO+XKL6i1P/Kb6EIbdmz+RDcuIMI5ZPVl+kw991ITbGqXNO57zwk8XQrGonfwt1h5gYYaeLu+do7YtiDFnVDRLdFhvB4SZNmen2s+uuUKYeVy4KPEAz9PXTIEG2DW8FJGlNsqpflBM+5CNDBlw6UJTSH2NtH4qFymJcIDmgf1yQ8zyc9W31EM3L38bqV5cbSM5ClzPaZB2E376LkemzJsd5qAtuO6SwLviQTnQ5uMFYaHfYtR6ENfHky9jo6tjuaV3CosZY2eBZN3vLegukGkqvLLquJd5CHJa/aR4JIiDMtkR2298EmF4J9+p2HPQCJAjc3HixXEHwN4VGWXMfgYuBp/1IKQF8kB3iC66qGwXOfo=
branches:
  only:
    - source
